### ISSUE TITLE
Apply dynamics delay in mapo_policy.apply_gradients_with_delays

### ISSUE THREAD

**Issue by thiagopbueno** [thiagopbueno/model-aware-policy-optimization#80]
It seems that for PGA learning there should be a `dynamics_delay`; the same way there is an `actor_delay` in `mapo_policy.apply_gradients_with_delays`...

Also, it seems weird that `critic_op` depend on `dynamics_op`:

```python
with tf.control_dependencies([dynamics_op]):
            critic_op = tf.cond(
                should_apply_critic_opt,
                true_fn=lambda: optimizer.critic.apply_gradients(critic_grads_and_vars),
                false_fn=tf.no_op,
            )
``` 

I think that in term of dependencies we should have:
1.  `dynamics_op` depending on the `critic_op`, and 
2. `actor_op` depending on `dynamics_op`...

What do you think @angelolovatto ?

**Comment by 0xangelo** [comment]
Hmm, okay. I was assuming that some component (actor, critic or dynamics) would get updated every optimization step, otherwise we would waste experiences. But it doesn't hurt to have delays for all three since that's more general.

I agree it makes sense to have the dynamics be updated after, and maybe less frequently than, the critic. In fact, our model-aware gradient might be highly dependent on the critic estimation quality, so it makes sense to update it more frequently.
